name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.8.4', '9.2.5', '9.4.4', '9.6.1']
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build
      - run: cabal run Nekomata -- -c '"Hello, World!"'
      - run: cabal run Nekomata -- -c '+' -i '1 2'
      - run: cabal run Nekomata-test
