name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.0.2', '9.6.7', '9.10.2', '9.12.2']
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build
      - run: cabal run Nekomata -- -c '"Hello, World!"'
      - run: cabal run Nekomata -- -c '+' -i '1 2'
      - run: cabal test --enable-test
